version: '3.4'

networks:
  taste_purchase_network:

services:
  taste_purchase_web:
    container_name: taste_purchase_container
    build:
      context: ./Docker/app
      args:
        - USER_ID=${DOCKER_UID}
        - GROUP_ID=${DOCKER_GID}
    command: gunicorn --bind 0.0.0.0:8000 web.wsgi
    env_file:
      - .env
    networks:
      taste_purchase_network:
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./Docker/app/source:/app
  fake_smtp:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    networks:
      taste_purchase_network:
        aliases:
          - smtp.netbuilder.local
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"