version: '3.4'

networks:
  taste_purchase_network:

services:
  taste_purchase_web:
    container_name: taste_purchase_container
    image: teambuilding/taste-and-purchase-dev
    command: gunicorn teambuilding.www.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    expose:
      - 8000
    networks:
      taste_purchase_network:
    user: user
    volumes:
      - ./Docker/app/source:/usr/src/www/app

  reverse_proxy:
    container_name: nginx_container
    build:
      context: ./Docker/nginx
    depends_on:
      - taste_purchase_web
    networks:
      taste_purchase_network:
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./Docker/app/source/static:/home/user/www/app/static

  fake_smtp:
    container_name: fake_smtp_container
    image: mailhog/mailhog
    logging:
      driver: 'none'
    networks:
      taste_purchase_network:
        aliases:
          - smtp.netbuilder.local
    ports:
      - "127.0.0.1:8025:8025"
