version: '3.4'

networks:
  teambuilding_network:

services:
  teambuilding_web:
    container_name: teambuilding_container
    image: netbuilderita/teambuilding-app-dev
    command: gunicorn www.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    expose:
      - 8000
    networks:
      teambuilding_network:
    user: user
    volumes:
      - ./Docker/app/source:/usr/src/www/app

  reverse_proxy:
    container_name: nginx_container
    build:
      context: ./Docker/nginx
    depends_on:
      - teambuilding_web
    networks:
      teambuilding_network:
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./Docker/app/source:/home/user/www/app

  fake_smtp:
    container_name: fake_smtp_container
    image: mailhog/mailhog
    logging:
      driver: 'none'
    networks:
      teambuilding_network:
        aliases:
          - smtp.netbuilder.local
    ports:
      - "127.0.0.1:8025:8025"
